//
// CompletionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension BlackmanClientAPI {


open class CompletionsAPI {

    /**

     - parameter completionRequest: (body)  
     - parameter xProviderApiKey: (header) Optional provider API key to override stored or system keys (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func completions(completionRequest: CompletionRequest, xProviderApiKey: String? = nil, apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: CompletionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return completionsWithRequestBuilder(completionRequest: completionRequest, xProviderApiKey: xProviderApiKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /v1/completions
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter completionRequest: (body)  
     - parameter xProviderApiKey: (header) Optional provider API key to override stored or system keys (optional)
     - returns: RequestBuilder<CompletionResponse> 
     */
    open class func completionsWithRequestBuilder(completionRequest: CompletionRequest, xProviderApiKey: String? = nil) -> RequestBuilder<CompletionResponse> {
        let localVariablePath = "/v1/completions"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: completionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Provider-Api-Key": xProviderApiKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CompletionResponse>.Type = BlackmanClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
