//
// FeedbackAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension BlackmanClientAPI {


open class FeedbackAPI {

    /**
     Submit feedback for a completion response
     
     - parameter submitFeedbackRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitFeedback(submitFeedbackRequest: SubmitFeedbackRequest, apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: SubmitFeedbackResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitFeedbackWithRequestBuilder(submitFeedbackRequest: submitFeedbackRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit feedback for a completion response
     - POST /v1/feedback
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter submitFeedbackRequest: (body)  
     - returns: RequestBuilder<SubmitFeedbackResponse> 
     */
    open class func submitFeedbackWithRequestBuilder(submitFeedbackRequest: SubmitFeedbackRequest) -> RequestBuilder<SubmitFeedbackResponse> {
        let localVariablePath = "/v1/feedback"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitFeedbackRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SubmitFeedbackResponse>.Type = BlackmanClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
