//
// SemanticCacheAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

extension BlackmanClientAPI {


open class SemanticCacheAPI {

    /**
     Get semantic cache configuration for the current account
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getConfig(apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: SemanticCacheConfig?, _ error: Error?) -> Void)) -> RequestTask {
        return getConfigWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get semantic cache configuration for the current account
     - GET /v1/semantic-cache/config
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<SemanticCacheConfig> 
     */
    open class func getConfigWithRequestBuilder() -> RequestBuilder<SemanticCacheConfig> {
        let localVariablePath = "/v1/semantic-cache/config"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SemanticCacheConfig>.Type = BlackmanClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get semantic cache statistics including hit rate and savings
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStats(apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: SemanticCacheStats?, _ error: Error?) -> Void)) -> RequestTask {
        return getStatsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get semantic cache statistics including hit rate and savings
     - GET /v1/semantic-cache/stats
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<SemanticCacheStats> 
     */
    open class func getStatsWithRequestBuilder() -> RequestBuilder<SemanticCacheStats> {
        let localVariablePath = "/v1/semantic-cache/stats"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SemanticCacheStats>.Type = BlackmanClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Invalidate all cache entries for the current account
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func invalidateAll(apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: InvalidateResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return invalidateAllWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Invalidate all cache entries for the current account
     - DELETE /v1/semantic-cache/invalidate
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<InvalidateResponse> 
     */
    open class func invalidateAllWithRequestBuilder() -> RequestBuilder<InvalidateResponse> {
        let localVariablePath = "/v1/semantic-cache/invalidate"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InvalidateResponse>.Type = BlackmanClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update semantic cache configuration for the current account
     
     - parameter semanticCacheConfig: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateConfig(semanticCacheConfig: SemanticCacheConfig, apiResponseQueue: DispatchQueue = BlackmanClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return updateConfigWithRequestBuilder(semanticCacheConfig: semanticCacheConfig).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update semantic cache configuration for the current account
     - PUT /v1/semantic-cache/config
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter semanticCacheConfig: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func updateConfigWithRequestBuilder(semanticCacheConfig: SemanticCacheConfig) -> RequestBuilder<Void> {
        let localVariablePath = "/v1/semantic-cache/config"
        let localVariableURLString = BlackmanClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: semanticCacheConfig)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = BlackmanClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
}
