//
// Choice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.Choice")
public typealias Choice = BlackmanClientAPI.Choice

extension BlackmanClientAPI {

public struct Choice: Codable, JSONEncodable, Hashable {

    public static let indexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var finishReason: String?
    public var index: Int
    public var message: Message

    public init(finishReason: String? = nil, index: Int, message: Message) {
        self.finishReason = finishReason
        self.index = index
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case finishReason = "finish_reason"
        case index
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(finishReason, forKey: .finishReason)
        try container.encode(index, forKey: .index)
        try container.encode(message, forKey: .message)
    }
}

}
