//
// CompletionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.CompletionResponse")
public typealias CompletionResponse = BlackmanClientAPI.CompletionResponse

extension BlackmanClientAPI {

public struct CompletionResponse: Codable, JSONEncodable, Hashable {

    public var choices: [Choice]
    public var created: Int64
    public var id: String
    public var model: String
    public var provider: Provider
    public var usage: Usage

    public init(choices: [Choice], created: Int64, id: String, model: String, provider: Provider, usage: Usage) {
        self.choices = choices
        self.created = created
        self.id = id
        self.model = model
        self.provider = provider
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case choices
        case created
        case id
        case model
        case provider
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(choices, forKey: .choices)
        try container.encode(created, forKey: .created)
        try container.encode(id, forKey: .id)
        try container.encode(model, forKey: .model)
        try container.encode(provider, forKey: .provider)
        try container.encode(usage, forKey: .usage)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BlackmanClientAPI.CompletionResponse: Identifiable {}
