//
// CompletionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.CompletionRequest")
public typealias CompletionRequest = BlackmanClientAPI.CompletionRequest

extension BlackmanClientAPI {

public struct CompletionRequest: Codable, JSONEncodable, Hashable {

    public static let maxTokensRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var maxTokens: Int?
    public var stop: [String]?
    public var stream: Bool?
    public var temperature: Float?
    public var topP: Float?
    public var messages: [Message]
    /** Optional metadata for tracking, analytics, and conditional processing. Can include session IDs, user context, feature flags, or any custom data. This metadata is logged with the request and can be used for filtering/analysis. */
    public var metadata: AnyCodable?
    public var model: String
    public var provider: Provider

    public init(maxTokens: Int? = nil, stop: [String]? = nil, stream: Bool? = nil, temperature: Float? = nil, topP: Float? = nil, messages: [Message], metadata: AnyCodable? = nil, model: String, provider: Provider) {
        self.maxTokens = maxTokens
        self.stop = stop
        self.stream = stream
        self.temperature = temperature
        self.topP = topP
        self.messages = messages
        self.metadata = metadata
        self.model = model
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxTokens = "max_tokens"
        case stop
        case stream
        case temperature
        case topP = "top_p"
        case messages
        case metadata
        case model
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxTokens, forKey: .maxTokens)
        try container.encodeIfPresent(stop, forKey: .stop)
        try container.encodeIfPresent(stream, forKey: .stream)
        try container.encodeIfPresent(temperature, forKey: .temperature)
        try container.encodeIfPresent(topP, forKey: .topP)
        try container.encode(messages, forKey: .messages)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(model, forKey: .model)
        try container.encode(provider, forKey: .provider)
    }
}

}
