//
// CompletionOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.CompletionOptions")
public typealias CompletionOptions = BlackmanClientAPI.CompletionOptions

extension BlackmanClientAPI {

public struct CompletionOptions: Codable, JSONEncodable, Hashable {

    public static let maxTokensRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var maxTokens: Int?
    public var stop: [String]?
    public var stream: Bool?
    public var temperature: Float?
    public var topP: Float?

    public init(maxTokens: Int? = nil, stop: [String]? = nil, stream: Bool? = nil, temperature: Float? = nil, topP: Float? = nil) {
        self.maxTokens = maxTokens
        self.stop = stop
        self.stream = stream
        self.temperature = temperature
        self.topP = topP
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxTokens = "max_tokens"
        case stop
        case stream
        case temperature
        case topP = "top_p"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxTokens, forKey: .maxTokens)
        try container.encodeIfPresent(stop, forKey: .stop)
        try container.encodeIfPresent(stream, forKey: .stream)
        try container.encodeIfPresent(temperature, forKey: .temperature)
        try container.encodeIfPresent(topP, forKey: .topP)
    }
}

}
