//
// ContentPart.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.ContentPart")
public typealias ContentPart = BlackmanClientAPI.ContentPart

extension BlackmanClientAPI {

/** Content part for multimodal messages (vision support) */
public enum ContentPart: Codable, JSONEncodable, Hashable {
    case typeContentPartOneOf(ContentPartOneOf)
    case typeContentPartOneOf1(ContentPartOneOf1)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeContentPartOneOf(let value):
            try container.encode(value)
        case .typeContentPartOneOf1(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ContentPartOneOf.self) {
            self = .typeContentPartOneOf(value)
        } else if let value = try? container.decode(ContentPartOneOf1.self) {
            self = .typeContentPartOneOf1(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ContentPart"))
        }
    }
}

}
