//
// ContentPartOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.ContentPartOneOf1")
public typealias ContentPartOneOf1 = BlackmanClientAPI.ContentPartOneOf1

extension BlackmanClientAPI {

public struct ContentPartOneOf1: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case imageUrl = "image_url"
    }
    public var imageUrl: ImageUrl
    public var type: ModelType

    public init(imageUrl: ImageUrl, type: ModelType) {
        self.imageUrl = imageUrl
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageUrl = "image_url"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(type, forKey: .type)
    }
}

}
