//
// ImageUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.ImageUrl")
public typealias ImageUrl = BlackmanClientAPI.ImageUrl

extension BlackmanClientAPI {

public struct ImageUrl: Codable, JSONEncodable, Hashable {

    /** Optional detail level: \"auto\", \"low\", or \"high\" */
    public var detail: String?
    public var url: String

    public init(detail: String? = nil, url: String) {
        self.detail = detail
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case detail
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encode(url, forKey: .url)
    }
}

}
