//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.Message")
public typealias Message = BlackmanClientAPI.Message

extension BlackmanClientAPI {

public struct Message: Codable, JSONEncodable, Hashable {

    public var content: MessageContent
    /** \"user\", \"assistant\", \"system\" */
    public var role: String

    public init(content: MessageContent, role: String) {
        self.content = content
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
        try container.encode(role, forKey: .role)
    }
}

}
