//
// MessageContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.MessageContent")
public typealias MessageContent = BlackmanClientAPI.MessageContent

extension BlackmanClientAPI {

/** Message content can be either a simple string or an array of content parts (for vision) */
public enum MessageContent: Codable, JSONEncodable, Hashable {
    case typeString(String)
    case type[ContentPart]([ContentPart])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeString(let value):
            try container.encode(value)
        case .type[ContentPart](let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else if let value = try? container.decode([ContentPart].self) {
            self = .type[ContentPart](value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of MessageContent"))
        }
    }
}

}
