//
// Provider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.Provider")
public typealias Provider = BlackmanClientAPI.Provider

extension BlackmanClientAPI {

public enum Provider: String, Codable, CaseIterable {
    case openAI = "OpenAI"
    case anthropic = "Anthropic"
    case gemini = "Gemini"
    case mistral = "Mistral"
    case groq = "Groq"
}
}
