//
// SemanticCacheStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.SemanticCacheStats")
public typealias SemanticCacheStats = BlackmanClientAPI.SemanticCacheStats

extension BlackmanClientAPI {

public struct SemanticCacheStats: Codable, JSONEncodable, Hashable {

    public static let tokensSavedRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalHitsRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalMissesRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Average similarity score for cache hits */
    public var avgSimilarityScore: Double
    /** Total cost saved from cache hits */
    public var costSaved: Double
    /** Cache hit rate as a percentage */
    public var hitRate: Double
    /** Total tokens saved from cache hits */
    public var tokensSaved: Int64
    /** Total number of cache hits */
    public var totalHits: Int64
    /** Total number of cache misses */
    public var totalMisses: Int64

    public init(avgSimilarityScore: Double, costSaved: Double, hitRate: Double, tokensSaved: Int64, totalHits: Int64, totalMisses: Int64) {
        self.avgSimilarityScore = avgSimilarityScore
        self.costSaved = costSaved
        self.hitRate = hitRate
        self.tokensSaved = tokensSaved
        self.totalHits = totalHits
        self.totalMisses = totalMisses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avgSimilarityScore = "avg_similarity_score"
        case costSaved = "cost_saved"
        case hitRate = "hit_rate"
        case tokensSaved = "tokens_saved"
        case totalHits = "total_hits"
        case totalMisses = "total_misses"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(avgSimilarityScore, forKey: .avgSimilarityScore)
        try container.encode(costSaved, forKey: .costSaved)
        try container.encode(hitRate, forKey: .hitRate)
        try container.encode(tokensSaved, forKey: .tokensSaved)
        try container.encode(totalHits, forKey: .totalHits)
        try container.encode(totalMisses, forKey: .totalMisses)
    }
}

}
