//
// SemanticCacheConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.SemanticCacheConfig")
public typealias SemanticCacheConfig = BlackmanClientAPI.SemanticCacheConfig

extension BlackmanClientAPI {

public struct SemanticCacheConfig: Codable, JSONEncodable, Hashable {

    /** Whether semantic caching is enabled */
    public var enabled: Bool
    /** Similarity threshold for cache hits (0.0-1.0) */
    public var similarityThreshold: Double
    /** Time-to-live for cache entries in seconds */
    public var ttlSeconds: Int64

    public init(enabled: Bool, similarityThreshold: Double, ttlSeconds: Int64) {
        self.enabled = enabled
        self.similarityThreshold = similarityThreshold
        self.ttlSeconds = ttlSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case similarityThreshold = "similarity_threshold"
        case ttlSeconds = "ttl_seconds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(similarityThreshold, forKey: .similarityThreshold)
        try container.encode(ttlSeconds, forKey: .ttlSeconds)
    }
}

}
