//
// SubmitFeedbackResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.SubmitFeedbackResponse")
public typealias SubmitFeedbackResponse = BlackmanClientAPI.SubmitFeedbackResponse

extension BlackmanClientAPI {

public struct SubmitFeedbackResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var message: String

    public init(id: String, message: String) {
        self.id = id
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(message, forKey: .message)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BlackmanClientAPI.SubmitFeedbackResponse: Identifiable {}
