//
// SubmitFeedbackRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.SubmitFeedbackRequest")
public typealias SubmitFeedbackRequest = BlackmanClientAPI.SubmitFeedbackRequest

extension BlackmanClientAPI {

public struct SubmitFeedbackRequest: Codable, JSONEncodable, Hashable {

    /** True for thumbs up, false for thumbs down */
    public var isPositive: Bool
    /** Optional metadata (e.g., user_agent, session_id, etc.) */
    public var metadata: AnyCodable?
    /** The response ID from the completion request */
    public var responseId: String

    public init(isPositive: Bool, metadata: AnyCodable? = nil, responseId: String) {
        self.isPositive = isPositive
        self.metadata = metadata
        self.responseId = responseId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isPositive = "is_positive"
        case metadata
        case responseId = "response_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isPositive, forKey: .isPositive)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(responseId, forKey: .responseId)
    }
}

}
