//
// Usage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "BlackmanClientAPI.Usage")
public typealias Usage = BlackmanClientAPI.Usage

extension BlackmanClientAPI {

public struct Usage: Codable, JSONEncodable, Hashable {

    public static let completionTokensRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let promptTokensRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalTokensRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var completionTokens: Int
    public var promptTokens: Int
    public var totalTokens: Int

    public init(completionTokens: Int, promptTokens: Int, totalTokens: Int) {
        self.completionTokens = completionTokens
        self.promptTokens = promptTokens
        self.totalTokens = totalTokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completionTokens = "completion_tokens"
        case promptTokens = "prompt_tokens"
        case totalTokens = "total_tokens"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(completionTokens, forKey: .completionTokens)
        try container.encode(promptTokens, forKey: .promptTokens)
        try container.encode(totalTokens, forKey: .totalTokens)
    }
}

}
